# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title:              Developers
description:        Integrating with Ledger Live
lang:               en

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo:               ledger.png

navbar:
    sticky:         true
    search:         true

# Social icons displayed in footer
social:
    github:         https://github.com/LedgerHQ
    reddit:         https://www.reddit.com/r/ledgerwallet/
    twitter:        https://twitter.com/Ledger
    youtube:        https://youtube.com/Ledger
    instagram:      https://www.instagram.com/ledger
    facebook:       https://www.facebook.com/Ledger
    linkedin:       https://fr.linkedin.com/company/ledgerhq

    email:
    website:        # https://ledger.com/
    flickr:
    dribbble:
    googleplus:
    pinterest:
    vimeo:

twitter:
  username: ledger

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        username # Enable by adding Twitter handle
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      Copyright © <a href="https://ledger.com/">Ledger</a> SAS. All rights reserved. <br>Ledger, Ledger Nano S, Ledger Vault, Bolos are registered trademarks of Ledger SAS.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics: GTM-W5FKZ2N

# Algolia search
algolia:
  application_id: 'WV98VMIU7C'
  index_name: dev_portal
  search_only_api_key: 2c01f0f02f9134bbd0e7fa5f1c5e6818
  extensions_to_index:
      - md
  settings:                                                                      
    searchableAttributes:                                                        
    - title                                                                    
    - unordered(categories)                                                    
    - unordered(tags)                                                          
    - unordered(content)                                                       
    customRanking:  

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: :expanded

plugins:
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
  # image for social media cards   
  - scope:
      path: ""
    values:
      image: /assets/images/portal-intro.jpg

# Site subpath, e.g. /blog
# Site base hostname & protocol, e.g. http://example.com

# baseurl:            /
# url:                ""

# baseurl:            /
# url:               https://blog.ledger.com
# url:               http://developers.ledger.com # 2021-06-09 1658


